#! /usr/local/bin/perl
use strict;
use warnings;
use Cwd;
use lib cwd;
use Selenium::Remote::Driver;
use Selenium::Chrome;
use Selenium::Firefox;
use Selenium::Remote::WDKeys;

use Data::Dumper;
use YAML::XS 'LoadFile';
    
use 5.010;
use Path::Tiny qw(path);
use File::Copy "copy";
use UtilSubs;

my $filename = shift || die "No filename";

onlyWednesdays($filename);
